language: python
cache:
  directories:
    - /tmp/travis-cache

before_install:
  - sudo apt-get update
  - sudo apt-get install -y s3cmd

# https://zato.io/docs/admin/guide/install/index.html#operating-system-considerations
env:
  - MODE=packaging IMAGE=centos:7
  - MODE=packaging IMAGE=centos:7 PY_BINARY=python3
  - MODE=packaging IMAGE=ubuntu:16.04
  - MODE=packaging IMAGE=ubuntu:16.04 PY_BINARY=python3
  - MODE=packaging IMAGE=ubuntu:18.04
  - MODE=packaging IMAGE=ubuntu:18.04 PY_BINARY=python3
  - MODE=packaging IMAGE=debian:8
  - MODE=packaging IMAGE=debian:8 PY_BINARY=python3
  - MODE=packaging IMAGE=debian:9
  - MODE=packaging IMAGE=debian:9 PY_BINARY=python3
  # - MODE=packaging IMAGE=alpine:3.7
  # - MODE=packaging IMAGE=alpine:3.7 PY_BINARY=python3
  # - MODE=packaging IMAGE=alpine:3.8
  # - MODE=packaging IMAGE=alpine:3.8 PY_BINARY=python3
  # - MODE=packaging IMAGE=alpine:3.9
  # - MODE=packaging IMAGE=alpine:3.9 PY_BINARY=python3

sudo: required
os:
  - linux

matrix:
  allow_failures:
    - osx

notifications:
  email: false

script:
  - source .travis/test_${MODE}.sh
  - echo "Tests passed..Uploading packages"
  - s3cmd --help
  - s3cmd --access_key=$ZATO_S3_ACCESS_KEY --secret_key=$ZATO_S3_SECRET_KEY sync /tmp/travis-cache/packages/ $ZATO_S3_BUCKET_NAME/
  - echo "Packages uploaded"
